import type { Puzzle } from "./types";

export const puzzles: Puzzle[] = [
  // === BEGINNER PUZZLES (3) - Introduces turning and basic navigation ===
  {
    id: "beginner-1",
    title: "Corner Turn",
    difficulty: "easy",
    shortKidHint: "Turn right at the corner!",
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, dir: "E" },
    goal: { x: 2, y: 2 },
    obstacles: [{ x: 1, y: 1, type: "rock" }],
    collectibles: [{ x: 2, y: 0, type: "star" }],
    allowedCommands: ["MOVE", "TURN_RIGHT", "PICK_STAR"],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "beginner-2",
    title: "Two Turns",
    difficulty: "easy",
    shortKidHint: "Go around the water!",
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, dir: "E" },
    goal: { x: 4, y: 2 },
    obstacles: [
      { x: 2, y: 1, type: "water" },
      { x: 2, y: 2, type: "water" },
      { x: 2, y: 3, type: "water" },
    ],
    collectibles: [{ x: 2, y: 0, type: "star" }],
    allowedCommands: ["MOVE", "TURN_LEFT", "TURN_RIGHT", "PICK_STAR"],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "beginner-3",
    title: "Star Path",
    difficulty: "easy",
    shortKidHint: "Collect both stars!",
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, dir: "S" },
    goal: { x: 4, y: 4 },
    obstacles: [
      { x: 1, y: 1, type: "rock" },
      { x: 3, y: 3, type: "rock" },
    ],
    collectibles: [
      { x: 0, y: 2, type: "star" },
      { x: 2, y: 4, type: "star" },
    ],
    allowedCommands: ["MOVE", "TURN_LEFT", "TURN_RIGHT", "PICK_STAR"],
    successCondition: { reachGoal: true, collectAllStars: true },
  },

  // === INTERMEDIATE PUZZLES (4) - More complex paths, multiple stars ===
  {
    id: "intermediate-1",
    title: "Wall Maze",
    difficulty: "medium",
    shortKidHint: "Navigate around the walls!",
    gridSize: { rows: 6, cols: 6 },
    start: { x: 0, y: 0, dir: "E" },
    goal: { x: 5, y: 5 },
    obstacles: [
      { x: 2, y: 0, type: "wall" },
      { x: 2, y: 1, type: "wall" },
      { x: 2, y: 2, type: "wall" },
      { x: 3, y: 4, type: "wall" },
      { x: 4, y: 4, type: "wall" },
      { x: 5, y: 4, type: "wall" },
    ],
    collectibles: [
      { x: 1, y: 1, type: "star" },
      { x: 4, y: 3, type: "star" },
    ],
    allowedCommands: ["MOVE", "TURN_LEFT", "TURN_RIGHT", "PICK_STAR"],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "intermediate-2",
    title: "Island Path",
    difficulty: "medium",
    shortKidHint: "Cross between the water pools!",
    gridSize: { rows: 6, cols: 6 },
    start: { x: 0, y: 2, dir: "E" },
    goal: { x: 5, y: 3 },
    obstacles: [
      { x: 1, y: 0, type: "water" },
      { x: 1, y: 1, type: "water" },
      { x: 2, y: 1, type: "water" },
      { x: 3, y: 3, type: "water" },
      { x: 3, y: 4, type: "water" },
      { x: 4, y: 4, type: "water" },
      { x: 4, y: 5, type: "water" },
    ],
    collectibles: [
      { x: 2, y: 0, type: "star" },
      { x: 5, y: 5, type: "star" },
    ],
    allowedCommands: ["MOVE", "TURN_LEFT", "TURN_RIGHT", "PICK_STAR"],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "intermediate-3",
    title: "Rock Field",
    difficulty: "medium",
    shortKidHint: "Weave through the rocks!",
    gridSize: { rows: 6, cols: 6 },
    start: { x: 0, y: 0, dir: "S" },
    goal: { x: 5, y: 5 },
    obstacles: [
      { x: 1, y: 1, type: "rock" },
      { x: 3, y: 1, type: "rock" },
      { x: 2, y: 2, type: "rock" },
      { x: 4, y: 2, type: "rock" },
      { x: 1, y: 3, type: "rock" },
      { x: 3, y: 4, type: "rock" },
      { x: 5, y: 3, type: "rock" },
    ],
    collectibles: [
      { x: 0, y: 2, type: "star" },
      { x: 2, y: 4, type: "star" },
      { x: 4, y: 5, type: "star" },
    ],
    allowedCommands: ["MOVE", "TURN_LEFT", "TURN_RIGHT", "PICK_STAR"],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "intermediate-4",
    title: "Double Loop",
    difficulty: "medium",
    shortKidHint: "Use Repeat x2 to save commands!",
    gridSize: { rows: 6, cols: 6 },
    start: { x: 0, y: 0, dir: "E" },
    goal: { x: 5, y: 0 },
    obstacles: [
      { x: 2, y: 0, type: "wall" },
      { x: 2, y: 1, type: "wall" },
      { x: 4, y: 1, type: "wall" },
      { x: 4, y: 2, type: "wall" },
    ],
    collectibles: [
      { x: 1, y: 2, type: "star" },
      { x: 3, y: 2, type: "star" },
      { x: 5, y: 2, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },

  // === ADVANCED PUZZLES (4) - Larger grids, more obstacles, repeat commands ===
  {
    id: "advanced-1",
    title: "Spiral Maze",
    difficulty: "hard",
    shortKidHint: "Spiral inward to the goal!",
    gridSize: { rows: 7, cols: 7 },
    start: { x: 0, y: 0, dir: "E" },
    goal: { x: 3, y: 3 },
    obstacles: [
      { x: 0, y: 2, type: "wall" },
      { x: 1, y: 2, type: "wall" },
      { x: 2, y: 2, type: "wall" },
      { x: 3, y: 2, type: "wall" },
      { x: 4, y: 2, type: "wall" },
      { x: 4, y: 3, type: "wall" },
      { x: 4, y: 4, type: "wall" },
      { x: 3, y: 4, type: "wall" },
      { x: 2, y: 4, type: "wall" },
    ],
    collectibles: [
      { x: 6, y: 0, type: "star" },
      { x: 6, y: 6, type: "star" },
      { x: 0, y: 6, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "advanced-2",
    title: "Water World",
    difficulty: "hard",
    shortKidHint: "Find the safe path through water!",
    gridSize: { rows: 7, cols: 7 },
    start: { x: 0, y: 3, dir: "E" },
    goal: { x: 6, y: 3 },
    obstacles: [
      { x: 1, y: 1, type: "water" },
      { x: 1, y: 2, type: "water" },
      { x: 1, y: 4, type: "water" },
      { x: 1, y: 5, type: "water" },
      { x: 3, y: 0, type: "water" },
      { x: 3, y: 1, type: "water" },
      { x: 3, y: 2, type: "water" },
      { x: 3, y: 4, type: "water" },
      { x: 3, y: 5, type: "water" },
      { x: 3, y: 6, type: "water" },
      { x: 5, y: 1, type: "water" },
      { x: 5, y: 2, type: "water" },
      { x: 5, y: 4, type: "water" },
      { x: 5, y: 5, type: "water" },
    ],
    collectibles: [
      { x: 2, y: 0, type: "star" },
      { x: 4, y: 3, type: "star" },
      { x: 2, y: 6, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "advanced-3",
    title: "Mixed Terrain",
    difficulty: "hard",
    shortKidHint: "Avoid rocks, water, and walls!",
    gridSize: { rows: 7, cols: 7 },
    start: { x: 0, y: 0, dir: "S" },
    goal: { x: 6, y: 6 },
    obstacles: [
      { x: 1, y: 0, type: "rock" },
      { x: 2, y: 1, type: "water" },
      { x: 0, y: 2, type: "wall" },
      { x: 3, y: 2, type: "rock" },
      { x: 4, y: 1, type: "water" },
      { x: 5, y: 2, type: "wall" },
      { x: 2, y: 3, type: "water" },
      { x: 4, y: 3, type: "rock" },
      { x: 1, y: 4, type: "wall" },
      { x: 3, y: 5, type: "water" },
      { x: 5, y: 4, type: "rock" },
      { x: 6, y: 4, type: "wall" },
      { x: 4, y: 6, type: "water" },
    ],
    collectibles: [
      { x: 0, y: 3, type: "star" },
      { x: 3, y: 3, type: "star" },
      { x: 6, y: 2, type: "star" },
      { x: 2, y: 6, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "advanced-4",
    title: "Corridor Run",
    difficulty: "hard",
    shortKidHint: "Use repeat to speed through!",
    gridSize: { rows: 8, cols: 8 },
    start: { x: 0, y: 0, dir: "E" },
    goal: { x: 7, y: 7 },
    obstacles: [
      { x: 0, y: 2, type: "wall" },
      { x: 1, y: 2, type: "wall" },
      { x: 2, y: 2, type: "wall" },
      { x: 3, y: 2, type: "wall" },
      { x: 4, y: 2, type: "wall" },
      { x: 5, y: 2, type: "wall" },
      { x: 6, y: 2, type: "wall" },
      { x: 1, y: 4, type: "wall" },
      { x: 2, y: 4, type: "wall" },
      { x: 3, y: 4, type: "wall" },
      { x: 4, y: 4, type: "wall" },
      { x: 5, y: 4, type: "wall" },
      { x: 6, y: 4, type: "wall" },
      { x: 7, y: 4, type: "wall" },
      { x: 0, y: 6, type: "wall" },
      { x: 1, y: 6, type: "wall" },
      { x: 2, y: 6, type: "wall" },
      { x: 3, y: 6, type: "wall" },
      { x: 4, y: 6, type: "wall" },
      { x: 5, y: 6, type: "wall" },
      { x: 6, y: 6, type: "wall" },
    ],
    collectibles: [
      { x: 7, y: 1, type: "star" },
      { x: 0, y: 3, type: "star" },
      { x: 7, y: 5, type: "star" },
      { x: 0, y: 7, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },

  // === EXPERT PUZZLES (4) - Maximum challenge ===
  {
    id: "expert-1",
    title: "Grand Labyrinth",
    difficulty: "hard",
    shortKidHint: "Find the path through the maze!",
    gridSize: { rows: 8, cols: 8 },
    start: { x: 0, y: 0, dir: "S" },
    goal: { x: 7, y: 7 },
    obstacles: [
      { x: 2, y: 0, type: "wall" },
      { x: 2, y: 1, type: "wall" },
      { x: 2, y: 2, type: "wall" },
      { x: 0, y: 2, type: "wall" },
      { x: 4, y: 0, type: "wall" },
      { x: 4, y: 1, type: "wall" },
      { x: 4, y: 2, type: "wall" },
      { x: 4, y: 3, type: "wall" },
      { x: 6, y: 1, type: "wall" },
      { x: 6, y: 2, type: "wall" },
      { x: 6, y: 3, type: "wall" },
      { x: 1, y: 4, type: "wall" },
      { x: 2, y: 4, type: "wall" },
      { x: 3, y: 4, type: "wall" },
      { x: 5, y: 5, type: "wall" },
      { x: 6, y: 5, type: "wall" },
      { x: 7, y: 5, type: "wall" },
      { x: 2, y: 6, type: "wall" },
      { x: 3, y: 6, type: "wall" },
      { x: 4, y: 6, type: "wall" },
      { x: 0, y: 6, type: "wall" },
    ],
    collectibles: [
      { x: 1, y: 1, type: "star" },
      { x: 5, y: 2, type: "star" },
      { x: 7, y: 4, type: "star" },
      { x: 0, y: 5, type: "star" },
      { x: 5, y: 7, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "expert-2",
    title: "Danger Zone",
    difficulty: "hard",
    shortKidHint: "Navigate the hazardous terrain!",
    gridSize: { rows: 8, cols: 8 },
    start: { x: 0, y: 3, dir: "E" },
    goal: { x: 7, y: 4 },
    obstacles: [
      { x: 1, y: 1, type: "water" },
      { x: 2, y: 1, type: "water" },
      { x: 1, y: 2, type: "water" },
      { x: 3, y: 2, type: "rock" },
      { x: 4, y: 1, type: "rock" },
      { x: 5, y: 2, type: "water" },
      { x: 6, y: 1, type: "water" },
      { x: 6, y: 2, type: "water" },
      { x: 2, y: 4, type: "wall" },
      { x: 2, y: 5, type: "wall" },
      { x: 3, y: 5, type: "wall" },
      { x: 4, y: 4, type: "rock" },
      { x: 5, y: 5, type: "water" },
      { x: 6, y: 6, type: "water" },
      { x: 1, y: 6, type: "rock" },
      { x: 3, y: 7, type: "wall" },
      { x: 4, y: 7, type: "wall" },
    ],
    collectibles: [
      { x: 0, y: 0, type: "star" },
      { x: 7, y: 0, type: "star" },
      { x: 4, y: 3, type: "star" },
      { x: 0, y: 7, type: "star" },
      { x: 6, y: 7, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "expert-3",
    title: "Diamond Hunt",
    difficulty: "hard",
    shortKidHint: "Collect all stars in the diamond!",
    gridSize: { rows: 9, cols: 9 },
    start: { x: 0, y: 4, dir: "E" },
    goal: { x: 8, y: 4 },
    obstacles: [
      // Diamond shape walls
      { x: 4, y: 0, type: "wall" },
      { x: 3, y: 1, type: "wall" },
      { x: 5, y: 1, type: "wall" },
      { x: 2, y: 2, type: "wall" },
      { x: 6, y: 2, type: "wall" },
      { x: 1, y: 3, type: "wall" },
      { x: 7, y: 3, type: "wall" },
      { x: 1, y: 5, type: "wall" },
      { x: 7, y: 5, type: "wall" },
      { x: 2, y: 6, type: "wall" },
      { x: 6, y: 6, type: "wall" },
      { x: 3, y: 7, type: "wall" },
      { x: 5, y: 7, type: "wall" },
      { x: 4, y: 8, type: "wall" },
      // Inner obstacles
      { x: 4, y: 3, type: "water" },
      { x: 3, y: 4, type: "water" },
      { x: 5, y: 4, type: "water" },
      { x: 4, y: 5, type: "water" },
    ],
    collectibles: [
      { x: 4, y: 1, type: "star" },
      { x: 2, y: 4, type: "star" },
      { x: 6, y: 4, type: "star" },
      { x: 4, y: 7, type: "star" },
      { x: 4, y: 4, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
  {
    id: "expert-4",
    title: "Ultimate Quest",
    difficulty: "hard",
    shortKidHint: "The final challenge awaits!",
    gridSize: { rows: 9, cols: 9 },
    start: { x: 0, y: 0, dir: "S" },
    goal: { x: 8, y: 8 },
    obstacles: [
      // Scattered obstacles creating a complex maze
      { x: 2, y: 0, type: "rock" },
      { x: 1, y: 1, type: "water" },
      { x: 3, y: 1, type: "wall" },
      { x: 5, y: 0, type: "water" },
      { x: 6, y: 1, type: "rock" },
      { x: 0, y: 2, type: "wall" },
      { x: 2, y: 2, type: "water" },
      { x: 4, y: 2, type: "rock" },
      { x: 7, y: 2, type: "wall" },
      { x: 1, y: 3, type: "rock" },
      { x: 3, y: 3, type: "wall" },
      { x: 5, y: 3, type: "water" },
      { x: 8, y: 3, type: "rock" },
      { x: 2, y: 4, type: "wall" },
      { x: 4, y: 4, type: "water" },
      { x: 6, y: 4, type: "wall" },
      { x: 0, y: 5, type: "rock" },
      { x: 3, y: 5, type: "water" },
      { x: 5, y: 5, type: "rock" },
      { x: 7, y: 5, type: "water" },
      { x: 1, y: 6, type: "wall" },
      { x: 4, y: 6, type: "rock" },
      { x: 6, y: 6, type: "water" },
      { x: 8, y: 6, type: "wall" },
      { x: 2, y: 7, type: "water" },
      { x: 5, y: 7, type: "wall" },
      { x: 7, y: 7, type: "rock" },
      { x: 3, y: 8, type: "rock" },
      { x: 6, y: 8, type: "water" },
    ],
    collectibles: [
      { x: 4, y: 0, type: "star" },
      { x: 8, y: 0, type: "star" },
      { x: 0, y: 4, type: "star" },
      { x: 8, y: 4, type: "star" },
      { x: 0, y: 8, type: "star" },
      { x: 4, y: 8, type: "star" },
    ],
    allowedCommands: [
      "MOVE",
      "TURN_LEFT",
      "TURN_RIGHT",
      "PICK_STAR",
      "REPEAT_2",
      "REPEAT_3",
    ],
    successCondition: { reachGoal: true, collectAllStars: true },
  },
];

export function getPuzzleById(id: string): Puzzle | undefined {
  return puzzles.find((p) => p.id === id);
}

export function getWheelSegments() {
  const colors = [
    "#FF6B6B", // coral red
    "#4ECDC4", // teal
    "#45B7D1", // sky blue
    "#96CEB4", // sage green
    "#FFEAA7", // soft yellow
    "#DDA0DD", // plum
    "#98D8C8", // mint
    "#F7DC6F", // golden yellow
    "#FF8C42", // orange
    "#A8E6CF", // light green
    "#88D8B0", // seafoam
    "#FFB6C1", // light pink
    "#87CEEB", // sky
    "#DEB887", // tan
    "#B19CD9", // light purple
  ];

  return puzzles.map((puzzle, index) => ({
    id: puzzle.id,
    title: puzzle.title,
    difficulty: puzzle.difficulty,
    color: colors[index % colors.length],
  }));
}
